AllCops:
  Include:
    - '**/config.ru'
  Exclude:
    - 'db/*'
    - 'config/**/*'
    - '**/features/support/env.rb'
    - 'script/*'
    - 'spec/*'

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
